# Use Node image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Expose Vite port
EXPOSE 5173

# Run frontend
CMD ["npm", "run", "dev", "--", "--host"]
